config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'comfort' => 'pages#comfort'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def comfort
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yachts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
	<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"> Y-Performance Yachts <span class="caret"></span>
 	 </button>
 	 <ul class="dropdown-menu" role="menu">
    <li><a href="#">BlueMotion 550</a></li>
    <li><a href="#">YY27</a></li>
        <li class="divider"></li>
    <li><a href="#">Separated link</a></li>
  	</ul>      

       
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
          </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Y-Performance Yachts</h1>
<p><%= link_to 'comfort', comfort_path %> Performance Versatility</p>